export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_FORGOT_USER = 'LOGIN_FORGOT_USER'
export const LOGIN_FORGOT_USER_CLOSE = 'LOGIN_FORGOT_USER_CLOSE'
export const LOGIN_ERROR_CLOSE = 'LOGIN_ERROR_CLOSE'

export const CLOSE_APP = 'CLOSE_APP'
